//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class cari
    {
        public int id { get; set; }
        public Nullable<long> vkn_tckn { get; set; }
        public Nullable<long> kullanici_id { get; set; }
        public string cari_mail { get; set; }
        public string sifre { get; set; }
        public Nullable<long> cari_vkn_tckn { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string webadresi { get; set; }
        public string cep_no { get; set; }
        public string telefon_no { get; set; }
        public string dogum_yeri { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public string activationcode1 { get; set; }
        public string activationcode2 { get; set; }
        public Nullable<bool> isactivated { get; set; }
        public string resetpasscode { get; set; }
        public Nullable<int> passattempts { get; set; }
        public Nullable<int> tip { get; set; }
        public Nullable<bool> kilitlimi { get; set; }
        public Nullable<bool> acikhesapmi { get; set; }
        public Nullable<bool> mukellefmi { get; set; }
        public string vergi_dairesi { get; set; }
        public Nullable<long> vergi_numarasi { get; set; }
        public string ticaret_sicil_no { get; set; }
        public string not { get; set; }
        public string sgk_no { get; set; }
        public Nullable<int> bagkur_no { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public SelectList DropDownList { get; set; }
        public SelectList DropDownListForCariTipi { get; set; }
        public IPagedList<cari_adres> cari_adresler { get; set; }
    }
}
