//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class cari_adres
    {
        public int id { get; set; }
        public Nullable<int> cari_id { get; set; }
        public string adres { get; set; }
        public Nullable<int> ulke_kodu { get; set; }
        public string ulke_adi { get; set; }
        public Nullable<int> il_kodu { get; set; }
        public string il_adi { get; set; }
        public Nullable<int> ilce_kodu { get; set; }
        public string ilce_adi { get; set; }
        public string cep_no { get; set; }
        public string telefon_no { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public Nullable<bool> faturaadresimi { get; set; }
        public Nullable<bool> sevkadresimi { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public SelectList DropDownListForUlke { get; set; }
        public SelectList DropDownListForIl { get; set; }
        public SelectList DropDownListForIlce { get; set; }
        public SelectList DropDownListForAdr { get; set; }
        public SelectList DropDownListForSevk { get; set; }
        public string ulke_il_ilce
        {
            get
            {
                return ulke_adi.Trim() != "" ? ulke_adi.Trim() + " / " : "" + il_adi.Trim() != "" ? il_adi.Trim() + " / " : "" + ilce_adi;
            }
            set { }
        }
    }
}
