//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using Fatura.UTL;
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class fatura
    {
        public int id { get; set; }
        public Nullable<long> vkn_tckn { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> cari_id { get; set; }
        public Nullable<int> doviz_id { get; set; }
        public Nullable<decimal> doviz_kuru { get; set; }
        public Nullable<int> islem_tipi { get; set; }
        public Nullable<decimal> aratoplam { get; set; }
        public Nullable<decimal> toplam_iskonto { get; set; }
        public Nullable<decimal> toplam_kdvtutar { get; set; }
        public Nullable<decimal> toplam_tevkifat { get; set; }
        public Nullable<decimal> toplam_otvtutar { get; set; }
        public Nullable<decimal> toplam_oivtutar { get; set; }
        public Nullable<decimal> toplam_fiyat { get; set; }
        public string seri { get; set; }
        public Nullable<int> sira_no { get; set; }
        public string belgeno { get; set; }
        public Nullable<System.DateTime> fatura_tarihi { get; set; }
        public Nullable<System.DateTime> sevk_tarihi { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> fatura_onaykontrol { get; set; }
        public string aciklama { get; set; }
        public string fatura_guid { get; set; }
        public string fatura_alias { get; set; }
        public Nullable<bool> mail_gittimi { get; set; }
        public string fatura_durum { get; set; }
        public string satis_iban { get; set; }
        public Nullable<int> entegrator_tipi { get; set; }
        public Nullable<int> fatura_tipi { get; set; }
        public Nullable<decimal> toplam_gvsmatrah { get; set; }
        public Nullable<decimal> toplam_gvstutar { get; set; }
        public Nullable<decimal> toplam_btumatrah { get; set; }
        public Nullable<decimal> toplam_btututar { get; set; }
        public Nullable<decimal> toplam_mfvmatrah { get; set; }
        public Nullable<decimal> toplam_mfvtutar { get; set; }
        public Nullable<decimal> toplam_sgkmatrah { get; set; }
        public Nullable<decimal> toplam_sgktutar { get; set; }
        public Nullable<decimal> toplam_smmgvsmatrah { get; set; }
        public Nullable<decimal> toplam_smmgvstutar { get; set; }
        public string not { get; set; }
        public string teslim_alan { get; set; }
        public string teslim_eden { get; set; }
        public Nullable<System.DateTime> teslim_tarihi { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public string cari_adi { get; set; }
        public SelectList DropDownListForFaturaTipi { get; set; }
        public SelectList DropDownListForDoviz { get; set; }
        public SelectList DropDownListForIslemTipi { get; set; }
        public SelectList DropDownListForFaturaAlias { get; set; }
        public SelectList DropDownListForSatisIban { get; set; }
        public string doviz_cinsi_ack { get; set; }
        public string fatura_tipi_ack
        {
            get
            {
                return Utilities.FaturaTipleri[(int)this.fatura_tipi];
            }
            set { }
        }
        public IPagedList<fatura_satir> detays { get; set; }
    }
}
