//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using Fatura.UTL;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class fatura_ayarlari
    {
        public int id { get; set; }
        public Nullable<long> vkn_tckn { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> fatura_tipi { get; set; }
        public Nullable<bool> testmi { get; set; }
        public Nullable<long> test_gndrn_vkn { get; set; }
        public Nullable<long> test_alici_vkn { get; set; }
        public Nullable<int> entegrator_tipi { get; set; }
        public string kullanici_adi { get; set; }
        public string sifre { get; set; }
        public string seri { get; set; }
        public Nullable<bool> seri_kullanilsinmi { get; set; }
        public string giden_fatura_tipi { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public SelectList DropDownListForFaturaTipi { get; set; }
        public SelectList DropDownListForFaturaTuru { get; set; }
        public SelectList DropDownListForEntegratorTipi { get; set; }
        public SelectList DropDownListForTestmi { get; set; }
        public SelectList DropDownListForSeriKullanilsinmi { get; set; }
        public string fatura_tipi_ack
        {
            get
            {
                return Utilities.FaturaTipleri[(int)this.fatura_tipi];
            }
            set { }
        }
        public string entegrator_tipi_ack
        {
            get
            {
                return Utilities.EntegratorTipleri[(int)this.entegrator_tipi];
            }
            set { }
        }
        public string kullanici_adsoyad { get; set; }
    }
}
