//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.Web.Mvc;

    public partial class firma
    {
        public int id { get; set; }
        public long vkn_tckn { get; set; }
        public string unvan { get; set; }
        public string vergi_dairesi { get; set; }
        public string ticaret_sicil_no { get; set; }
        public string adres { get; set; }
        public Nullable<int> ulke_kodu { get; set; }
        public string ulke_adi { get; set; }
        public Nullable<int> il_kodu { get; set; }
        public string il_adi { get; set; }
        public Nullable<int> ilce_kodu { get; set; }
        public string ilce_adi { get; set; }
        public string email { get; set; }
        public string web_sitesi { get; set; }
        public string subdomain { get; set; }
        public string telefon { get; set; }
        public string fax { get; set; }
        public string iban1 { get; set; }
        public string iban2 { get; set; }
        public string iban3 { get; set; }
        public string notlar { get; set; }
        public Nullable<System.DateTime> lisans_bitis_tarihi { get; set; }
        public string emailUserName { get; set; }
        public string emailUserPassword { get; set; }
        public string emailDisplayName { get; set; }
        public string smtpServerName { get; set; }
        public Nullable<int> smtpServerPort { get; set; }
        public Nullable<bool> smtpServerSSLEnable { get; set; }
        public string logo { get; set; }
        public string kase { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public SelectList DropDownList { get; set; }
        public virtual HttpPostedFileBase logoFile { get; set; }
        public virtual HttpPostedFileBase kaseFile { get; set; }
        public SelectList DropDownListForUlke { get; set; }
        public SelectList DropDownListForIl { get; set; }
        public SelectList DropDownListForIlce { get; set; }
    }
}
