//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id { get; set; }
        public long vkn_tckn { get; set; }
        public int kullanici_id { get; set; }
        public string controller { get; set; }
        public string method { get; set; }
        public string tablo_adi { get; set; }
        public string url { get; set; }
        public string hata { get; set; }
        public string bilgi { get; set; }
        public string ip_adresi { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
