//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class faturaEntities : DbContext
    {
        public faturaEntities()
            : base("name=faturaDataSet")
        {
        }
        public faturaEntities(String subdomain)
            : base("name=" + subdomain)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<barkodlar> barkodlars { get; set; }
        public virtual DbSet<birimler> birimlers { get; set; }
        public virtual DbSet<cari> caris { get; set; }
        public virtual DbSet<cari_adres> cari_adres { get; set; }
        public virtual DbSet<depolar> depolars { get; set; }
        public virtual DbSet<dil_cevirileri> dil_cevirileri { get; set; }
        public virtual DbSet<diller> dillers { get; set; }
        public virtual DbSet<dovizler> dovizlers { get; set; }
        public virtual DbSet<fatura> faturas { get; set; }
        public virtual DbSet<fatura_ayarlari> fatura_ayarlari { get; set; }
        public virtual DbSet<fatura_gelen> fatura_gelen { get; set; }
        public virtual DbSet<fatura_gelen_satir> fatura_gelen_satir { get; set; }
        public virtual DbSet<fatura_satir> fatura_satir { get; set; }
        public virtual DbSet<firma> firmas { get; set; }
        public virtual DbSet<fiyat_tipleri> fiyat_tipleri { get; set; }
        public virtual DbSet<kodlar> kodlars { get; set; }
        public virtual DbSet<kullanici> kullanicis { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<stok> stoks { get; set; }
        public virtual DbSet<stok_barkod> stok_barkod { get; set; }
        public virtual DbSet<stok_birim> stok_birim { get; set; }
        public virtual DbSet<stok_fiyat> stok_fiyat { get; set; }
        public virtual DbSet<ticaret_ayarlari> ticaret_ayarlari { get; set; }
        public virtual DbSet<ulke_il_ilce> ulke_il_ilce { get; set; }
        public virtual DbSet<vergi> vergis { get; set; }
        public virtual DbSet<mukellef> mukellefs { get; set; }
    }
}
