//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mukellef
    {
        public string Title { get; set; }
        public Nullable<long> VergiKimlikNo { get; set; }
        public string PostBoxAlias { get; set; }
        public string SenderBoxAlias { get; set; }
        public string Tipi { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> recorddate { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public int id { get; set; }
    }
}
