//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class stok_birim
    {
        public int id { get; set; }
        public Nullable<int> stok_id { get; set; }
        public Nullable<int> birim_id { get; set; }
        public Nullable<decimal> katsayi { get; set; }
        public Nullable<decimal> agirlik { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public IPagedList<stok_fiyat> stok_fiyatlar { get; set; }
        public SelectList DropDownListFor { get; set; }
        public string birim_ack { get; set; }
    }
}
