//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class stok_fiyat
    {
        public int id { get; set; }
        public Nullable<int> depo_id { get; set; }
        public Nullable<int> stok_birim_id { get; set; }
        public Nullable<int> doviz_id { get; set; }
        public Nullable<int> fiyat_tip { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public SelectList DropDownListForDoviz { get; set; }
        public SelectList DropDownListForFiyatTipi { get; set; }
        public string doviz_kodu { get; set; }
        public string fiyat_tip_ack { get; set; }
    }
}
