//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stok_barkod
    {
        public int id { get; set; }
        public int barkod_id { get; set; }
        public string barkodu { get; set; }
        public string barkod_text { get; set; }
        public int stok_id { get; set; }
        public bool isdeleted { get; set; }
        public System.DateTime last_update { get; set; }
        public System.Guid guid { get; set; }
    }
}
