//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatura.Entity
{
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.Web.Mvc;

    public partial class stok
    {
        public int id { get; set; }
        public Nullable<long> vkn_tckn { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public string kodu { get; set; }
        public string adi { get; set; }
        public Nullable<long> gtip_no { get; set; }
        public string resimler { get; set; }
        public Nullable<int> tedarik_yer_kodu { get; set; }
        public string tedarik_yer_adi { get; set; }
        public Nullable<decimal> kdv_orani { get; set; }
        public Nullable<decimal> otv_orani { get; set; }
        public Nullable<decimal> oiv_orani { get; set; }
        public Nullable<decimal> gvs_orani { get; set; }
        public Nullable<decimal> btu_orani { get; set; }
        public Nullable<decimal> mfv_orani { get; set; }
        public Nullable<decimal> sgk_orani { get; set; }
        public Nullable<decimal> smm_gvs_orani { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public SelectList DropDownListForMensei { get; set; }
        public SelectList DropDownListForKdv { get; set; }
        public SelectList DropDownListForOtv { get; set; }
        public SelectList DropDownListForOiv { get; set; }
        public SelectList DropDownListForGvs { get; set; }
        public SelectList DropDownListForBtu { get; set; }
        public SelectList DropDownListForMfv { get; set; }
        public SelectList DropDownListForSgk { get; set; }
        public virtual HttpPostedFileBase resimFile { get; set; }
        public IPagedList<stok_birim> stok_birimler { get; set; }
        public Nullable<int> birim_id_son { get; set; }
        public Nullable<int> doviz_id_son { get; set; }
        public Nullable<decimal> fiyat_son { get; set; }
    }
}
